@domain = http://localhost:3000
@AccessToken = {{loginToken.response.body.$.accessToken}}

### 
# 예매 전체 조회
GET {{domain}}/payment
Authorization: Bearer {{AccessToken}}

###
# 예매 상세 조회
GET {{domain}}/payment/1
Authorization: Bearer {{AccessToken}}

###
# 로그인 - user
# @name loginToken
POST {{domain}}/user/login
Content-Type: application/json

{
   "email": "sss33@gmail.com",
   "password": "sss33"
} 

###
# 로그인 - admin
# @name loginToken
POST {{domain}}/user/login
Content-Type: application/json

{
    "email": "ooo@gmail.com",
    "password": "ooo11"
} 

### 
#예매 전체 조회
GET {{domain}}/payment/all/34
Authorization: Bearer {{AccessToken}}
 
###
# 예매 생성
POST {{domain}}/payment/create/28
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InMwMF95QG5hdmVyLmNvbSIsInN1YiI6ImRmVHBuOGtoVGtEWG11bld2WWoxaEhabTJSajh4UzR1ZFo5RW9JaGF3Y2ciLCJpYXQiOjE3MDQyNDY4MjZ9.IEzt75KptDN1LDfzLfob9Pp5YspSgIvICY3g8u1Z0BA
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "seats":[
        {
            "grade": "S",
            "seat_num": 5
        },
        {
            "grade": "S",
            "seat_num": 6
        }
    ],
    "schedule_id":42
}


###
# 예매 취소
DELETE  {{domain}}/payment/187
Authorization: Bearer {{AccessToken}}
 