@domain = http://localhost:3000
@AccessToken = {{loginToken.response.body.$.accessToken}}


###
# 공연 전체 조회
GET {{domain}}/performance

###
# 특정 공연 조회
GET {{domain}}/performance/1

###
# 로그인
# @name loginToken
POST {{domain}}/user/login
Content-Type: application/json

{
    "email": "ex04@gmail.com",
    "password": "qwerty04"
}   
 
###
# 사용자가 등록한 공연 전체 조회
GET {{domain}}/performance/user/11
Authorization: Bearer {{AccessToken}}

###
# 공연 등록 - Admin
POST {{domain}}/performance/create
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "title": "공연 제목1",
    "content": "공연 내용3",
    "location": "인천시 동구",
    "start_at": "2023년 12월 28일 수요일 20시",
    "end_at": "2023년 12월 28일 수요일 22시"
} 

###
# 공연 수정 - Admin
PATCH  {{domain}}/performance/5
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "content": "공연 내용1"
}

###
# 공연 삭제 - Admin
DELETE {{domain}}/performance/5
Authorization: Bearer {{AccessToken}}
