@domain = http://localhost:3000
@AccessToken = {{loginToken.response.body.$.accessToken}}


###
# 공연 전체 조회
GET {{domain}}/performance

###
# 공연 검색 조회
GET {{domain}}/performance/search?keyword=렌트

###
# 공연 상세 조회
GET {{domain}}/performance/9

###
# 로그인
# @name loginToken
POST {{domain}}/user/login
Content-Type: application/json

{
    "email": "soo@gmail.com",
    "password": "soo10"
}   
 
###
# 사용자가 등록한 공연 전체 조회
GET {{domain}}/performance/user/11
Authorization: Bearer {{AccessToken}}

###
# 공연 등록 - Admin
POST {{domain}}/performance/create
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "title": "뮤지컬 - 레베카",
    "content": "레베카",
    "location": "서울시",
    "schedule": ["2023년 12월 30일 토요일 20시", "2023년 12월 31일 일요일 20시", "2023년 12월 31일 월요일 20시"],
    "image": "imageurl://urlurl",
    "category":0,
     "times":1,
      "date":"2023-12-29",
      "start_at":"20:00",
      "end_at":"22:00"
} 
 
###
# 공연 수정 - Admin
PATCH  {{domain}}/performance/9
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "schedule": ["2023년 12월 28일 수요일 22시", "2023년 12월 28일 수요일 23시"]
}

###
# 공연 삭제 - Admin
DELETE {{domain}}/performance/8
Authorization: Bearer {{AccessToken}}
