@domain = http://localhost:3000
@AccessToken = {{loginToken.response.body.$.accessToken}}

###
# 회원가입
POST {{domain}}/user/register
Content-Type: application/json

{
    "email": "ex04@gmail.com",
    "name": "ex04",
    "password": "qwerty04"
} 

###
# 로그인
# @name loginToken
POST {{domain}}/user/login
Content-Type: application/json

{
    "email": "ex04@gmail.com",
    "password": "qwerty04"
}   

###
# 내 정보 조회
GET {{domain}}/user/4
Authorization: Bearer {{AccessToken}}

###
# 네이버 로그인
GET {{domain}}/user/naver/login

###
#
GET  {{domain}}/user/check
Authorization: Bearer {{AccessToken}}
