@domain = http://localhost:3000
@AccessToken = {{loginToken.response.body.$.accessToken}}

###
# 회원가입
POST {{domain}}/user/register
Content-Type: application/json

{
    "email": "ex07@gmail.com",
    "name": "ex07",
    "password": "qwerty07",
    "role": 0
} 

###
# 로그인
# @name loginToken
POST {{domain}}/user/login
Content-Type: application/json

{
    "email": "ex07@gmail.com",
    "password": "qwerty07"
}   

###
# 내 정보 조회
GET {{domain}}/user/17
Authorization: Bearer {{AccessToken}}

###
# 네이버 로그인
GET {{domain}}/user/naver/login

###
#
GET  {{domain}}/user/check
Authorization: Bearer {{AccessToken}}
